### ISSUE TITLE
Subgradient-based interval refinement

### ISSUE THREAD

**Issue by ca0h** [PSORLab/EAGO.jl#29]
Is "subgradient-based interval refinement" removed from EAGO? If so, is it possible that we can have it back? Thanks.

**Comment by mewilhel** [comment]
The "sub-gradient-based interval refinement" is still a part of EAGO. I may have commented it out on the master a while ago when working on debugging a separate part of the package. I'm still merging work in a separate git repository with the main EAGO.jl repository so the master is a bit of a mess and may have some bugs until that is finished.  I'll tag a new version at that point.

We've transitioned from a strictly method oriented approach to calculation which was embedded in a HybridSMC object to a hybrid approach. It appears in the standard evaluator as Passes.jl file as SetPost(). The motivation for this is that it lets us preallocate memory across multiple B&B subproblems and function evaluations and speed up calculations.

**Comment by mewilhel** [comment]
Issues resolved in new version of EAGO.
