### ISSUE TITLE
Compatibility issues with DiffRules in Julia 1.3

### ISSUE THREAD

**Issue by rcallen24** [PSORLab/EAGO.jl#38]
I am running into compatibility issues with DiffRules when I try to install EAGO in Julia 1.3, see below:

(v1.3) pkg> add EAGO
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package EAGO [bb8be931]:
EAGO [bb8be931] log:
|- possible versions are: [0.2.0-0.2.1, 0.3.0] or uninstalled
|- restricted to versions * by an explicit requirement, leaving only versions [0.2.0-0.2.1, 0.3.0]
|- restricted by compatibility requirements with JuMP [4076af6c] to versions: 0.3.0 or uninstalled, leaving only versions: 0.3.0
|-- JuMP [4076af6c] log:
|--- possible versions are: [0.18.3-0.18.6, 0.19.0-0.19.2, 0.20.0-0.20.1] or uninstalled
|--- restricted to versions 0.20.1 by an explicit requirement, leaving only versions 0.20.1
|- restricted by compatibility requirements with DiffRules [b552c78f] to versions: 0.2.0-0.2.1 or uninstalled — no versions left
|-- DiffRules [b552c78f] log:
|--- possible versions are: [0.0.8-0.0.10, 0.1.0, 1.0.0] or uninstalled
|--- restricted to versions 1.0.0 by an explicit requirement, leaving only versions 1.0.0

I was wondering if you have any advice as how to move forward.

**Comment by mewilhel** [comment]
Thanks for the feedback. It looks like you have an explicit requirement for DiffRules 1.0.0 somewhere. There are a few options to address this:

- If you can get by with a prior version of that package then EAGO should be compatible. So removing DiffRules, restarting Julia, and then reinstalling should allow the package to load. 
- If you need that version, then you can replace `DiffRules = "0.0.5, 0.0.10"` with `DiffRules = "0.0.5, 1.0.0"` in the compat section of your local copy of EAGO's Project.toml, restart Julia, and everything should work out. There aren't any functional compatibility issues with the new version, a version cap was just included as preemptive measure (and so we could tag a release via the package manager).

Normally, I'd just bump package requirements and issue a patch release to fix this (an EAGO 0.3.1, etc.) but I'm planning minor release as soon as I get resolution on a separate upstream issue (https://github.com/JuliaIntervals/IntervalContractors.jl/issues/39).

Let me know if you have any other questions or run into any other issues.

**Comment by mewilhel** [comment]
I believe we've resolved this with v0.4 of EAGO. Let us know if you have any future issues.

**Comment by mewilhel** [comment]
I think this and any similar future issues have been resolved by EAGO supporting  julia ~1 now. So I'm closing this out. If that is incorrect then I'll re-open this on request.
