### ISSUE TITLE
Consider not restricting compat for Julia to each minor version

### ISSUE THREAD

**Issue by KristofferC** [PSORLab/EAGO.jl#58]
For new versions in Julia we run the tests for all packages to look for regressions. This package (and some of its dependencies) restrict the Julia version compatibility to not be compatible with these new Julia versions:

https://github.com/PSORLab/EAGO.jl/blob/dac69e5925828818db929f155f95710959765ad7/Project.toml#L46

What happens when we try to run the tests for a new Julia version of this pacakge is that version EAGO v0.2.1 is installed because that one doesn't restrict the minor version:

https://github.com/JuliaRegistries/General/blob/fe561d17bf40e7bcf003ded665c45b336efe6ce1/E/EAGO/Compat.toml#L18

I would suggest just having

``` 
julia = "1"
``` 

in your project file instead. That would make it easier for us to thest the package on new Julia versions and ensure that eventual regressions would get caught.

**Comment by mewilhel** [comment]
Thanks for the heads up. I'll take a look into this shortly.

**Comment by mewilhel** [comment]
Looks like these packages that need to be updated prior to changing the Julia version supported by EAGO.jl.

- [ ] McCormick.j Need IntervalArithmetic.jl dependency to support version ~0.14 or lower.
- [ ] ReverseMcCormick.jl: Need McCormick.jl dependency to support julia 1. Need IntervalContractors.jl dependency version ~0.3 or lower.
- [ ]  IntervalArithmetic.jl: Need to support version ~0.14 or lower.
- [ ]  IntervalContractors.jl Need to support version ~0.3 or lower.

**Comment by mewilhel** [comment]
Closed by version v0.5.1.
