### ISSUE TITLE
Docs warn against CPLEX

### ISSUE THREAD

**Issue by odow** [PSORLab/EAGO.jl#78]
I saw this warning:
![image](https://user-images.githubusercontent.com/8177701/111090194-ca8f2e80-8593-11eb-8430-be7a7f3f6abe.png)

Can you comment on the specifics? If CPLEX has unexpected behavior, that is a bug that should be fixed.

**Comment by mewilhel** [comment]
I think this is primarily a relic from the early days of MathOptInterface when those wrappers were first being implemented. 

I'll be adding some additional unit testing for interactions with subproblem solvers in the next few weeks and I'll drop this from the documentation when I roll that out.

**Comment by mewilhel** [comment]
Resolved by v0.7.
